# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: interface                     # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Dieses Plugin liest die aktuellen Werte eines Solax-Wechselrichters per Modbus aus'
        en: 'This plug-in reads the current values of an Solax inverter via Modbus'
    maintainer: akreis
#    tester:                         # Who tests this plugin?
    state: develop                  # Initial 'develop'. change to 'ready' when done with development
#    keywords: iot xyz
#    documentation: ''              # An url to optional plugin doc - NOT the url to user_doc!!!
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 0.0.1                  # Plugin version (must match the version specified in __init__.py)

    # these min/max-versions MUST be given in quotes, or e.g. 3.10 will be interpreted as 3.1 (3.1 < 3.9 < 3.10)
    sh_minversion: '1.10'           # minimum shNG version to use this plugin
#    sh_maxversion: '1.11'          # maximum shNG version to use this plugin (omit if latest)
#    py_minversion: '3.10'          # minimum Python version to use for this plugin
#    py_maxversion: '4.25'          # maximum Python version to use for this plugin (omit if latest)

    multi_instance: false           # plugin supports multi instance
    restartable: unknown            # plugin supports stopping and starting again, must be implemented
    #configuration_needed: False     # False: The plugin will be enabled by the Admin GUI without configuration
    classname: solaxmodbus         # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    host:
        type: ipv4
        mandatory: True
        description:
            de: 'IP Adresse'
            en: 'ip address'
    
    port:
        type: int
        default: 502
        description:
            de: 'Modbus Port'
            en: 'modbus port'

    cycle:
        type: int
        default: 60
        description:
            de: 'Update Zyklus in Sekunden'
            en: 'update cycle time in seconds'





item_attributes:
    # Definition of item attributes defined by this plugin (enter 'item_attributes: NONE', if section should be empty)
    solax:
        type: str
        description:
            de: 'item to test'
            en: 'item to test'
    
    solax_inverter_type:
        type: str
        description:
            de: 'Typangabe des Wechselrichters'
            en: 'inverter type'
        valis_list:
            - 'X1-Hybrid G4'
            - 'X3-Hybrid G4'


item_structs:
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions:
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters:
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
